spring:
  application:
    name: Hack
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-242-84-130.eu-west-1.compute.amazonaws.com:5432/d47749r53cqacn
    username: nvicrfkvsqiukz
    password: 72cb063e2d15682a57574d2ac14a61e648d471dc9490d476df6236c832991ae4
  jpa:
    database: POSTGRESQL
  flyway:
    locations: classpath:db/migration, classpath:db/data
  sql:
    init:
      platform: postgres

server:
  port: 10880
  shutdown: graceful
  servlet:
    context-path: /api/v1

jwt:
  jwt-secret: "1#42?!@3321"
  time-of-action-auth-token: 1
  time-of-action-access-token: 24

out-system:
  systems:
    - name: "VTB"
      systemLink: "https://hackathon.lsp.team/hk"
      bearer: false