spring:
  application:
    name: Hack
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2rnKmkJG
  jpa:
    database: POSTGRESQL
  flyway:
    locations: classpath:db/migration, classpath:db/data
  sql:
    init:
      platform: postgres

server:
  port: 10880
  shutdown: graceful
  servlet:
    context-path: /api/v1

jwt:
  jwt-secret: "1#42?!@3321"
  time-of-action-auth-token: 1
  time-of-action-access-token: 24

out-system:
  systems:
    - name: "CoinDesk"
      systemLink: "https://api.coindesk.com/v1/"
      systemKey: ""
      bearer: false
    - name: "Nationalize"
      systemLink: "https://api.nationalize.io/"
      bearer: false