spring:
  application:
    name: Hack
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-91-223-99.compute-1.amazonaws.com:5432/d3o2eslh6jqdi0
    username: bqcmwqbvpipfez
    password: 9a80573372e3be6b557901c7caf0bea3db80546bd90c97e9dc3770f5287a66c0
  jpa:
    database: POSTGRESQL
  flyway:
    locations: classpath:db/migration, classpath:db/data
  sql:
    init:
      platform: postgres

server:
  port: 10880
  shutdown: graceful
  servlet:
    context-path: /api/v1

jwt:
  jwt-secret: "1#42?!@3321"
  time-of-action-auth-token: 1
  time-of-action-access-token: 24

out-system:
  systems:
    - name: "VTB"
      systemLink: "https://hackathon.lsp.team/hk"
      bearer: false

system-valet:
  private-key: 5dfd7f093e1f356f98274cb77af3f5d2e14944de57c6dc27c4cbd36d6e43ea1a